#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin

echo ""
echo "Starting Thirty Two Bit"
echo ""

#
# Mount pseudo-filesystems
#

echo "Mounting /proc..."
mount -t proc proc /proc
echo "Mounting /sys..."
mount -t sysfs sysfs /sys

# Optional but good
mount -t devtmpfs devtmpfs /dev 2>/dev/null

# fallback
if [ $? -ne 0 ]; then
	echo "Setting up basic /dev so mdev can take over..."
	mkdir -p /dev/
	[ -e /dev/null ]	|| mknod /dev/null c 1 3
	[ -e /dev/console ]	|| mknod /dev/console c 5 1
	[ -e /dev/tty ]		|| mknod /dev/tty c 5 0
fi

#
# Start mdev
#

echo "Starting mdev..."

mkdir -p /dev/pts
mkdir -p /dev/shm

mount -t devpts devpts /dev/pts
mount -t tmpfs tmpfs /dev/shm

echo /sbin/mdev > /proc/sys/kernel/hotplug

mdev -s

#
# Mount other fses
#

mount -a

#
# Networking
#

echo "Bringing up loopback..."
ifconfig lo 127.0.0.1 up

for i in /sys/class/net/*; do
	iface=$(basename "$i")
	[ "$iface" = "lo" ] && continue
	echo "Bringing up $iface..."
	ifconfig "$iface" up
	echo "Starting DHCP on $iface..."
	udhcpc -i "$iface"
done

#
# Swap
#

#swapon -a

# 
# Cleanup
#

echo "Cleaning stuff up from /var/run and /var/lock..."
mkdir -p /var/run
mkdir -p /var/lock

rm -f /var/run/*.pid
rm -f /var/lock/*

#
# Logging
#

#echo "Starting system logging..."
#syslogd
#klogd

#
# Clock
#

#if [ -x /sbin/hwclock ]; then
#	hwclock --hctosys
#fi

#
# Banner
#

clear

echo " _____ _____ ____  "
echo "|_   _|_   _| __ ) "
echo "  | |   | | |  _ \ "
echo "  | |   | | | |_) |"
echo "  |_|   |_| |____/ "
echo " "
