# Written by vmunix. If something goes wrong, yell at me.

KERNEL=./386linux
# Where the kernel is located

ROOT=../root
# Where the rootfs for the i386 system is located

CROSS=../cross
# Where the tools for cross compiling to the i386 system is located

MUSL_CROSS=cross

# C flags for compiling musl
CFLAGS=-m32 -march=i386 -mtune=i386 -fcf-protection=none -fno-stack-protector -fomit-frame-pointer -mno-mmx -mno-sse -fno-pic -Os

# C compiler for compiling musl
CC=cc

help:
	@echo "You should probably read the wiki."
	@echo "FIXME"

kernel-env:
	# @echo "[NOTE] executing 'make headers_install ARCH=i386 INSTALL_HDR_PATH=../$(CROSS)'"
	cd $(KERNEL) && make headers_install ARCH=i386 INSTALL_HDR_PATH=$(CROSS)

musl:
	# echo "[NOTE] executing 'cd musl-1.2.5 && CFLAGS='$(CFLAGS) -I${PWD}/${MUSL_CROSS}/include')' ./configure --target=i386 --prefix= '${PWD}/${MUSL_CROSS}'"
	# @echo "[NOTE] executing 'cd musl-1.2.5 && CFLAGS='$(CFLAGS) -I../cross/include' ./configure --target=i386 --prefix= '../cross'"
	# cd musl-1.2.5 && CFLAGS="$(CFLAGS) -I$(realpath "${PWD}/${CROSS}/include")" ./configure --target=i386 --prefix=$(realpath "${PWD}/../${CROSS}")
	cd musl-1.2.5 && CFLAGS='$(CFLAGS) -I../cross/include' ./configure --target=i386 --prefix='../cross'
